# Generated by Django 5.2.12 on 2026-03-19 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_batchjob_invoicejob_delete_uploadeddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchjob',
            name='used_for_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoicejob',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicejob',
            name='used_for_training',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('invoices_used', models.IntegerField(default=0)),
                ('epochs', models.IntegerField(default=5)),
                ('best_f1', models.FloatField(blank=True, null=True)),
                ('model_path', models.CharField(blank=True, max_length=500)),
                ('log', models.TextField(blank=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('invoices_trained_on', models.IntegerField(default=0)),
                ('model_path', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('training_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='converter.trainingrun')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
    ]
